import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { MswProvider } from "../../providers/MswProvider";
import { ReactQueryProvider } from "../../providers/ReactQueryProvider";
import {
  NextIntlClientProvider,
  getMessages,
  locales,
  setRequestLocale,
} from "@repo/i18n";
import { notFound } from "next/navigation";

type Props = {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
};

const geistSans = localFont({
  src: "../../fonts/GeistVF.woff",
  variable: "--font-geist-sans",
});
const geistMono = localFont({
  src: "../../fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: Readonly<Props>) {
  const { locale } = await params;

  if (!locales.includes(locale as any)) {
    notFound();
  }

  setRequestLocale(locale as any);
  const messages = await getMessages();
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <MswProvider>
          <ReactQueryProvider>
            <NextIntlClientProvider messages={messages}>
              {children}
            </NextIntlClientProvider>
          </ReactQueryProvider>
        </MswProvider>
      </body>
    </html>
  );
}
