import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import { MswProvider } from '../../../providers/MswProvider';
import { ReactQueryProvider } from '../../../providers/ReactQueryProvider';

import { notFound } from 'next/navigation';
import { Header } from '@/features/templates';
import { locales } from '@/i18n/locales';
import { Locale } from '@/i18n';
import { getMessages, setRequestLocale } from 'next-intl/server';
import { NextIntlClientProvider } from 'next-intl';

type Props = {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
};

const geistSans = localFont({
  src: '../../fonts/GeistVF.woff',
  variable: '--font-geist-sans',
});
const atkinsonMono = localFont({
  src: [
    {
      path: '../../fonts/AtkinsonHyperlegibleMono-VariableFont_wght.ttf',
      style: 'normal',
    },
    {
      path: '../../fonts/AtkinsonHyperlegibleMono-Italic-VariableFont_wght.ttf',
      style: 'italic',
    },
  ],
  variable: '--font-atkinson-mono',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({ children, params }: Readonly<Props>) {
  const { locale } = await params;

  if (!locales.includes(locale as Locale)) {
    notFound();
  }

  const typedLocale = locale as Locale;
  setRequestLocale(typedLocale);
  const messages = await getMessages();
  return (
    <html lang="en">
      <body className={`${atkinsonMono.variable} ${geistSans.variable} `}>
        <MswProvider>
          <ReactQueryProvider>
            <NextIntlClientProvider messages={messages}>
              <Header locale={typedLocale} />
              {children}
            </NextIntlClientProvider>
          </ReactQueryProvider>
        </MswProvider>
      </body>
    </html>
  );
}
